In [1]:
import pandas as pd

In [2]:
messages=pd.read_csv('smsspamcollection/SMSSpamCollection',sep='\t',names=["label","message"])

In [3]:
messages

label                                            message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham               Will ü b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [4]:
import re
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/parthabhang/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [5]:
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer
porter=PorterStemmer()

In [6]:
corpus = []
for i  in range(0, len(messages)):
    review = re.sub('[^a-zA-z]','  ', messages['message'][i])
    review = review.lower() 
    review = review.split()
    review = [porter.stem(word)  for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review )

In [7]:
corpus

['go jurong point crazi avail bugi n great world la e buffet cine got amor wat',
 'ok lar joke wif u oni',
 'free entri wkli comp win fa cup final tkt st may text fa receiv entri question std txt rate c appli',
 'u dun say earli hor u c alreadi say',
 'nah think goe usf live around though',
 'freemsg hey darl week word back like fun still tb ok xxx std chg send rcv',
 'even brother like speak treat like aid patent',
 'per request mell mell oru minnaminungint nurungu vettam set callertun caller press copi friend callertun',
 'winner valu network custom select receivea prize reward claim call claim code kl valid hour',
 'mobil month u r entitl updat latest colour mobil camera free call mobil updat co free',
 'gonna home soon want talk stuff anymor tonight k cri enough today',
 'six chanc win cash pound txt csh send cost p day day tsandc appli repli hl info',
 'urgent week free membership prize jackpot txt word claim c www dbuk net lccltd pobox ldnw rw',
 'search right word thank breather

In [8]:
### Create bag of words

In [49]:
from sklearn.feature_extraction.text import CountVectorizer

In [48]:
x_train

['repli win weekli fifa world cup held send stop end servic',
 'hello sort town alreadi dont rush home eat nacho let know eta',
 'come guoyang go n tell u told',
 'hey sathya till dint meet even singl time saw situat sathya',
 'orang bring rington time chart hero free hit week go rington pic wap stop receiv tip repli stop',
 'sit mu wait everyon get suit take shower',
 'finish liao u',
 'urgent mobil award bonu caller prize nd attempt contact call box qu',
 'probabl still go stuff',
 'wah lucki man save money hee',
 'hey u still gym',
 'oh lk tt den take e one tt end cine lor dun wan yogasana oso',
 'ok lor',
 'still havent collect dough pl let know go place sent get control number',
 'stupid possibl',
 'u secret admir reveal think u r special call opt repli reveal stop per msg recd cust care',
 'amaz rearrang letter give mean dormitori dirti room astronom moon starer eye see elect result lie let recount mother law woman hitler eleven plu two twelv plu one amaz',
 'call listen extrem d

In [ ]:
cv = CountVectorizer(max_features=2500, ngram_range=(1,2))
x_train=cv.fit_transform(x_train).toarray()
x_test=cv.transform(x_test).toarray() 

In [11]:
import numpy as np

In [12]:
cv.vocabulary_

{'go': 791,
 'point': 1619,
 'crazi': 451,
 'avail': 112,
 'bugi': 237,
 'great': 858,
 'world': 2441,
 'la': 1104,
 'cine': 354,
 'got': 839,
 'wat': 2355,
 'ok': 1463,
 'lar': 1115,
 'joke': 1074,
 'wif': 2407,
 'oni': 1484,
 'ok lar': 1466,
 'free': 719,
 'entri': 622,
 'wkli': 2431,
 'comp': 402,
 'win': 2412,
 'cup': 468,
 'final': 687,
 'st': 2017,
 'may': 1266,
 'text': 2121,
 'receiv': 1734,
 'question': 1692,
 'std': 2030,
 'txt': 2231,
 'rate': 1709,
 'appli': 76,
 'free entri': 724,
 'entri wkli': 624,
 'cup final': 469,
 'std txt': 2031,
 'txt rate': 2237,
 'rate appli': 1711,
 'dun': 583,
 'say': 1843,
 'earli': 589,
 'alreadi': 49,
 'nah': 1375,
 'think': 2141,
 'goe': 814,
 'usf': 2297,
 'live': 1179,
 'around': 88,
 'though': 2149,
 'freemsg': 731,
 'hey': 940,
 'darl': 493,
 'week': 2375,
 'word': 2437,
 'back': 129,
 'like': 1165,
 'fun': 747,
 'still': 2033,
 'tb': 2101,
 'xxx': 2468,
 'send': 1882,
 'rcv': 1717,
 'even': 632,
 'brother': 225,
 'speak': 2001,
 'treat

In [15]:
### o/p feature

y=pd.get_dummies(messages['label']).astype(int)

In [19]:
y=y.iloc[:,1].values

In [20]:
y

array([0, 0, 1, ..., 0, 0, 0])

In [21]:
from sklearn.model_selection import train_test_split

In [47]:
x_train,x_test,y_train,y_test = train_test_split(corpus,y,test_size=0.20, random_state=42)

In [23]:
from sklearn.naive_bayes import MultinomialNB

In [51]:
spam_detect_model = MultinomialNB().fit(x_train,y_train)

In [52]:
spam_detect_model

MultinomialNB()

In [53]:
y_predicted=spam_detect_model.predict(x_test)

In [54]:
y_predicted

array([0, 0, 0, ..., 0, 0, 0])

In [55]:
y.shape

(5572,)

In [28]:
from sklearn.metrics import accuracy_score, classification_report

In [56]:
accuracy_score(y_test,y_predicted)

0.9838565022421525

In [57]:
print(classification_report(y_test,y_predicted))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99       966
           1       0.95      0.93      0.94       149

    accuracy                           0.98      1115
   macro avg       0.97      0.96      0.96      1115
weighted avg       0.98      0.98      0.98      1115



In [36]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [37]:
tfidf = TfidfVectorizer(max_features=2500,ngram_range=(1,2))
x=tfidf.fit_transform(corpus).toarray()

In [38]:
x

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [39]:
tfidf.vocabulary_

{'go': 791,
 'point': 1619,
 'crazi': 451,
 'avail': 112,
 'bugi': 237,
 'great': 858,
 'world': 2441,
 'la': 1104,
 'cine': 354,
 'got': 839,
 'wat': 2355,
 'ok': 1463,
 'lar': 1115,
 'joke': 1074,
 'wif': 2407,
 'oni': 1484,
 'ok lar': 1466,
 'free': 719,
 'entri': 622,
 'wkli': 2431,
 'comp': 402,
 'win': 2412,
 'cup': 468,
 'final': 687,
 'st': 2017,
 'may': 1266,
 'text': 2121,
 'receiv': 1734,
 'question': 1692,
 'std': 2030,
 'txt': 2231,
 'rate': 1709,
 'appli': 76,
 'free entri': 724,
 'entri wkli': 624,
 'cup final': 469,
 'std txt': 2031,
 'txt rate': 2237,
 'rate appli': 1711,
 'dun': 583,
 'say': 1843,
 'earli': 589,
 'alreadi': 49,
 'nah': 1375,
 'think': 2141,
 'goe': 814,
 'usf': 2297,
 'live': 1179,
 'around': 88,
 'though': 2149,
 'freemsg': 731,
 'hey': 940,
 'darl': 493,
 'week': 2375,
 'word': 2437,
 'back': 129,
 'like': 1165,
 'fun': 747,
 'still': 2033,
 'tb': 2101,
 'xxx': 2468,
 'send': 1882,
 'rcv': 1717,
 'even': 632,
 'brother': 225,
 'speak': 2001,
 'treat

In [40]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2, random_state=42)

In [41]:
spam_detect_model_tfidf = MultinomialNB().fit(x_train,y_train)

In [44]:
y_predicted_tfidf=spam_detect_model_tfidf.predict(x_test)

In [45]:
print(accuracy_score(y_test, y_predicted_tfidf))

0.9820627802690582


In [46]:
print(classification_report(y_test,y_predicted_tfidf))

              precision    recall  f1-score   support

           0       0.98      1.00      0.99       966
           1       0.99      0.87      0.93       149

    accuracy                           0.98      1115
   macro avg       0.99      0.94      0.96      1115
weighted avg       0.98      0.98      0.98      1115



In [59]:
import gensim

In [60]:
from gensim.models import word2vec, keyedvectors

In [61]:
import gensim.downloader as api

w2v = api.load('word2vec-google-news-300')

In [62]:
vec_king = w2v['king']

In [63]:
vec_king

array([ 1.25976562e-01,  2.97851562e-02,  8.60595703e-03,  1.39648438e-01,
       -2.56347656e-02, -3.61328125e-02,  1.11816406e-01, -1.98242188e-01,
        5.12695312e-02,  3.63281250e-01, -2.42187500e-01, -3.02734375e-01,
       -1.77734375e-01, -2.49023438e-02, -1.67968750e-01, -1.69921875e-01,
        3.46679688e-02,  5.21850586e-03,  4.63867188e-02,  1.28906250e-01,
        1.36718750e-01,  1.12792969e-01,  5.95703125e-02,  1.36718750e-01,
        1.01074219e-01, -1.76757812e-01, -2.51953125e-01,  5.98144531e-02,
        3.41796875e-01, -3.11279297e-02,  1.04492188e-01,  6.17675781e-02,
        1.24511719e-01,  4.00390625e-01, -3.22265625e-01,  8.39843750e-02,
        3.90625000e-02,  5.85937500e-03,  7.03125000e-02,  1.72851562e-01,
        1.38671875e-01, -2.31445312e-01,  2.83203125e-01,  1.42578125e-01,
        3.41796875e-01, -2.39257812e-02, -1.09863281e-01,  3.32031250e-02,
       -5.46875000e-02,  1.53198242e-02, -1.62109375e-01,  1.58203125e-01,
       -2.59765625e-01,  

In [64]:
messages

label                                            message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham               Will ü b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]